name: 'Build Debian Package'
description: 'Build Rust daemon and create .deb package using cargo-deb'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup cross-compilation
      uses: taiki-e/setup-cross-toolchain-action@v1
      with:
        target: aarch64-unknown-linux-musl

    - uses: Swatinem/rust-cache@v2
      with:
        key: aarch64-unknown-linux-musl

    - name: Install cargo-deb
      run: cargo install cargo-deb
      shell: bash

    - name: Build for aarch64
      run: cargo build --release --target aarch64-unknown-linux-musl
      shell: bash

    - name: Build Debian package with cargo-deb
      run: |
        # Build the halpi CLI tool as well (referenced in Cargo.toml assets)
        cargo build --release --target aarch64-unknown-linux-musl -p halpi

        # Read Debian version from file (written by generate-changelog.sh)
        if [ -f ".debian-version" ]; then
          DEB_VERSION=$(cat .debian-version)
          echo "Using Debian version from .debian-version: $DEB_VERSION"
          VERSION_FLAG="--deb-version=$DEB_VERSION"
        else
          echo "No .debian-version file found, using Cargo.toml version"
          VERSION_FLAG=""
        fi

        # Build the .deb package (--no-strip because host strip can't handle ARM64 binaries)
        cargo deb -p halpid --target aarch64-unknown-linux-musl --no-build --no-strip $VERSION_FLAG
      shell: bash

    - name: Move package to root
      run: |
        mv target/aarch64-unknown-linux-musl/debian/*.deb ./
      shell: bash

    - name: List generated packages
      run: |
        echo "📦 Generated packages:"
        ls -lh *.deb
      shell: bash
