name: 'Run Tests'
description: 'Run Rust checks and tests for HALPI2 rust-daemon'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2

    - name: Run cargo check
      run: cargo check --all-targets --verbose
      shell: bash

    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings
      shell: bash

    - name: Check formatting
      run: cargo fmt --all -- --check
      shell: bash

    - name: Run tests
      run: cargo test --verbose
      shell: bash
